### ISSUE TITLE
Timeouts connecting to BigChainDB

### ISSUE THREAD

**Issue by iChauster** [sidharthramesh/medblocks#6]
Hi,

First, great project!

I am trying to follow along and use medblocks, but it seems whenever it tries to access the blockchain/BigChainDB, there is a timeout error.

This may be something on the BCDB end -- or perhaps something with my configuration. Would you be able to explain how I can remedy this issue or any alternatives I can pursue?

**Comment by sidharthramesh** [comment]
Bigchain DB is depreciated. We are continuing the project with other alternatives.
